version: 2.1

orbs:
  node: circleci/node@4.1.0
  python: circleci/python@1.2.0

jobs:
  build-and-test-python:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout:
          path: ~/project
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run Python Tests
          command: |
            python3 ./database/jsonParser.py

  build-and-test-react:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: npm
          app-dir: ~/project/react-app
      - run:
          name: Build React app
          command: |
            cd ~/project/react-app
            npm run build
      - run:
          name: Run React tests
          command: |
            cd ~/project/react-app
            npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test-python
      - build-and-test-react
